baseURL = 'https://muratov.space/'
languageCode = 'en-us'
title = 'muratov.'
theme = 'muratov.space'
disableKinds = ["taxonomy", "term"]
enableGitInfo = true
enableRobotsTXT = true

[markup]
    [markup.highlight]
        style = 'dracula'

[params]
    twitter_handle = "@ramilmuratov"

[frontmatter]
    lastmod = ["lastmod", ":git", "date", "publishDate"]

[minify]
    [minify.tdewolff]
        [minify.tdewolff.html]
            keepQuotes = true